apiRules:
- include:
    uidRegex: ^Sainna
    type: Namespace
- include:
    uidRegex: ^Global
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace
- exclude:
    uidRegex: ^Sainna\.Utils